name: Build Go Binary

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    build:
        name: Build Go Binary
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4

            - name: Setup Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.21

            - name: Install Dependencies
              run: go mod tidy

            - name: Build Binary (Linux)
              env:
                  MEOW_USER_ID: ${{ secrets.MEOW_USER_ID }}
              run: go build -o webhook_linux main.go

            - name: Build Binary (Windows)
              env:
                  MEOW_USER_ID: ${{ secrets.MEOW_USER_ID }}
              run: GOOS=windows GOARCH=amd64 go build -o webhook_x64.exe main.go

            - name: Upload Binary Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: webhook-binaries
                  path: |
                      webhook_linux
                      webhook_x64.exe
